# PostgreSQL Database Configuration
spring.datasource.url=${postgresql://serviciotecnicoada_user:VUbPV5azsFKKxZDmuk7nozoHsr2FMlGP@dpg-cqumqurv2p9s73e3nlr0-a/serviciotecnicoada}
spring.datasource.username=${serviciotecnicoada_user}
spring.datasource.password=${VUbPV5azsFKKxZDmuk7nozoHsr2FMlGP}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Hibernate Configuration (remains the same)
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true